### ISSUE TITLE
Ease of use enhancements for auth-setup

### ISSUE THREAD

**Issue by keithchambers** [CiscoCloud/microservices-infrastructure#109]
It would be much simpler to digest security.json is it has a format similar to this:
```
{
    "user": {
        "marathon": {
            "credentials": [
                {
                    "user": "admin",
                    "secret": "vPcPxmbmHmwvB7bK"
                }
            ]
        }
    },
    "system": {
        "consul": {
            "default_acl_policy": "allow",
            "gossip_key": "98OiTuO3RhpTuwM5MC18bw==",
            "acl_master_token": "f3bf3637-5dfa-4927-b638-4faf4fc658d0",
            "agent_acl_token": "bcf982dd-9ddc-ce3b-edbc-3e2328b0be75"
        },
        "marathon": {
            "credentials": [
                {
                    "principal": "marathon",
                    "secret": "qILqip1mhIO+LcI87hruhLT/+poO9obDH9XnUDXNl8r1"
                }
            ]
        },
        "mesos": {
            "credentials": [
                {
                    "principal": "marathon",
                    "secret": "qILqip1mhIO+LcI87hruhLT/+poO9obDH9XnUDXNl8r1"
                },
                {
                    "principal": "follower",
                    "secret": "RDVkmEicmwrdcQjB/r+VmMVKSR0Vt20hN4YOJabrwETq"
                }
            ]
        },
        "zookeeper": {
            "credentials": [
                {
                    "user": "mesos",
                    "secret": "b2dUE39puRwgZZLj",
                    "secret_digest": "3mAZ67O10arlQ51OYglIYpoJnXk="
                },
                {
                    "user": "super",
                    "secret": "b3PQH/BBzfZ1pS+Dw5RoMq/KmJxky/SMMBCFjaH7USEM"
                },
                {
                    "user": "marathon",
                    "secret": "Wi0ufYJTnxjyVZvQ",
                    "secret_digest": "wqU2RVJ5HEgVvy6PA+1/wCh2zbY="
                }
            ],
            "consul_ssl_verify": "false",
            "consul_ssl": "true"
        }
    },
    "http_proxy": {
        "credentials": [
            {
                "user": "admin",
                "secret": "qWKhOkYwY3OzOshP"
            }
        ]
    }
}
```

**Comment by keithchambers** [comment]
Let's assume these are true if ```"principal": "marathon"``` and ```"principal": "follower"``` have secrets defined:

```
"mesos_authenticate_followers": true, 
"mesos_authenticate_frameworks": true,
```

**Comment by keithchambers** [comment]
Is ```"security_enabled": true,``` required?

**Comment by BrianHicks** [comment]
I assume you're asking if it would be more digestible for humans? I'm not sure that nesting that deeply would help, actually. While we're using Ansible, it would also make it much harder to consume, since the way Ansible consumes YAML will overwrite keys instead of merging them. So, for example, if we had some default somewhere in the `system.mesos` key we'd also have to override it in `security.json`. In this case a flatter namespace is *much* easier to manage. Sorting the keys may be possible, however.

The reason that `mesos_authenticate_{followers,frameworks}` are set explicitly is because not all frameworks support Mesos framework auth (although they really should.) I'm comfortable deriving the value automatically and will add a ticket for it. They will stay at the same location in the defaults, though, in case they need to be overridden.

`security_enabled` is used more as a signifier than anything else. It's used [in the first play in `site.yml`](https://github.com/CiscoCloud/microservices-infrastructure/blob/master/site.yml#L3-L12) to throw an error if security isn't enabled. Ideally, we could generate and load that variable automatically but the current set of Ansible playbooks doesn't have an option to load a bunch of variables from a JSON file without passing in the argument on the command line. Writing a module for that may be possible, but it might not be the best use of time.

**Comment by keithchambers** [comment]
@BrianHicks 

I'm good with alphabetical sorting for now so that it's more digestible for our users.

Since we are optimizing for Ansible a bit let's stick with the standard YAML.

Cool?

Here is some code from another project where we did some fancy sorting YAML that might be helpful:  https://gist.github.com/keithchambers/4f9e2b2618cb2ecf4085

**Comment by keithchambers** [comment]
```
{
  "users": [
    {
      "user": "admin",
      "secret": "vPcPxmbmH1wvB7bK",
      "enabled": 1,
      "pubkeys": [
        "ssh-rsa AAAA31ybB5yc2...",
        "ssh-rsa AAAAB3NzaC1yc..."
      ]
    },
    {
      "user": "kechambe",
      "secret": "vPcPx7Sufjmdwv7BKb",
      "enabled": 0,
      "pubkeys": [
        "ssh-rsa AAAA31ybB5yc2...",
        "ssh-rsa AAAAB3NzaC1yc..."
      ]
    }
  ],
  "servers": [
    {
      "zookeeper": {
        "credentials": [
          {
            "user": "mesos",
            "secret": "b2dUE39puRwgZZLj",
            "secret_digest": "3mAZ67O10arlQ51OYglIYpoJnXk="
          },
          {
            "user": "super",
            "secret": "b3PQH/BBzfZ1pS+Dw5RoMq/KmJxky/SMMBCFjaH7USEM"
          },
          {
            "user": "marathon",
            "secret": "Wi0ufYJTnxjyVZvQ",
            "secret_digest": "wqU2RVJ5HEgVvy6PA+1/wCh2zbY="
          }
        ],
        "consul_ssl_verify": "false",
        "consul_ssl": "true"
      },
      "mesos": {
        "credentials": [
          {
            "principal": "marathon",
            "secret": "qILqip1mhIO+LcI87hruhLT/+poO9obDH9XnUDXNl8r1"
          },
          {
            "principal": "follower",
            "secret": "RDVkmEicmwrdcQjB/r+VmMVKSR0Vt20hN4YOJabrwETq"
          }
        ]
      },
      "marathon": {
        "credentials": [
          {
            "principal": "marathon",
            "secret": "qILqip1mhIO+LcI87hruhLT/+poO9obDH9XnUDXNl8r1"
          }
        ]
      },
      "default_acl_policy": "allow",
      "gossip_key": "98OiTuO3RhpTuwM5MC18bw==",
      "acl_master_token": "f3bf3637-5dfa-4927-b638-4faf4fc658d0",
      "agent_acl_token": "bcf982dd-9ddc-ce3b-edbc-3e2328b0be75"
    }
  ]
}
```

**Comment by keithchambers** [comment]
Steve and I had a offline conversation yesterday.  We decided for the 0.2 tagged release we will:

1. Switch back to YAML from JSON for the `security` file.
2. Use a single unified password for the`admin` account across Consul, Marathon, and Mesos
3. Prompt the user for `admin` account password during `auth-setup`.  This will KISS for our Vagrant users.
4. Use Nginx to secure Mesos UI access on port 8080 with SSL
