### ISSUE TITLE
Create CI environment

### ISSUE THREAD

**Issue by keithchambers** [CiscoCloud/microservices-infrastructure#163]
CI system should:
* Automatically build all GH pull requests
* Automatically test all commits to master

Test case:
* Deploy fresh system to multiple regions (on Cisco Cloud Services)
* Deploy test application to multiple regions (on Cisco Cloud Services)

For the time being this won't be publicly accessible.

Keep it simple to start with.

**Comment by stevendborrelli** [comment]
Moving this to 0.3.1

**Comment by ohal** [comment]
actually, it is publicly accessible, but it might be what we want to see:

 * [ciscocloud jenkins ci documentation](https://github.com/CiscoCloud/microservices-infrastructure/blob/qa/features-master-integration/docs/jenkins_ci.md "ciscocloud jenkins ci documentation")
 * [jenkins ci](http://173.39.214.186/view/CCS-MI-US-INTERNAL-1-QA-1/ "jenkins ci")

**Comment by matjohn2** [comment]
This needs breaking down into smaller issues, this is an EPIC vs a STORY. Moving back into IceBox. This is a CI Environment for Building / Testing MI Itself. Before this issue can be started a design discussion will be held in a future sprint. This is covered in issue: #547

**Comment by stevendborrelli** [comment]
As per #622, we want to move to a terraform-based tool that we can use to deploy any branch to any cloud. Distributive will be our infrastructure testing tool. 

We'd like to run tests from drone running in an MI cluster.

**Comment by sharma-abhishek-it** [comment]
@stevendborrelli umm so we are not having jenkins then? Also is there some branch where I can see some test cases written or is that a WIP?

**Comment by siddharthist** [comment]
@sharma-abhishek-it Our Distributive checklists ca be found [here](https://github.com/CiscoCloud/distributive-rpm/tree/master/SOURCES). And yes, the current plan is to use Drone instead of Jenkins.

**Comment by ohal** [comment]
@sharma-abhishek-it 
- jenkins for watching is accessible here http://173.39.214.186/view/CCS-MI-US-INTERNAL-1-QA-1/ it continuosly deploys and does testing each commit and PR to the master and features-integration branches
- test cases written in robot-framework and currently they are not published, I suppose I will do PR to 
microservices-infrastructure github repo soon

@siddharthist 
 *And yes, the current plan is to use Drone instead of Jenkins. *
- that's cool, could you please show us current plan? is drone working somewhere? can be seen? i'm not sure, however distributive and drone are looking more like unit testing, not functional

**Comment by ohal** [comment]
here for review PR with robotframework code base https://github.com/CiscoCloud/microservices-infrastructure/pull/632

**Comment by stevendborrelli** [comment]
Closing this. For multi-cloud CI testing please refer to the implementation status in #874.
