### ISSUE TITLE
Marathon service offer ports

### ISSUE THREAD

**Issue by kenjones-cisco** [CiscoCloud/microservices-infrastructure#174]
Based on the marathon documentation (https://mesosphere.github.io/marathon/docs/native-docker.html) under *Static port mapping* there should be a way to set what ports are offered for resources to leverage. I'm looking to determine if the configurations are already part of the playbook and I missed it, or if possibly it was left as the default and not provided via any configurations thus far.

As part of my application I will ultimately need my application proxy to respond on port 80 or a way to auto redirect to an endpoint without a user ever needing to know it is not listening directly on port 80, and I have other resources like mongo that is typically on 27017.

A range of 31000 - 32000 could be quite limited if everything needs a port to go along with the ip address.

Any input would be greatly appreciated.

**Comment by stevendborrelli** [comment]
I agree with this approach. We also have a request to reduce the number of ports in the Vagrant environment. I'm thinking we could have a resource variable in the mesos role.

**Comment by keithchambers** [comment]
@kenjones-cisco in addition to Steven's comments, he and I are actively exploring how we can enhance Meso so that every task gets its own IP address. This way, every MongoDB task gets it's own IP and they can all listen on 27017.

We're also exploring floating IPs. With floating IPs, when a slave dies the tasks are relaunch on other slaves with the same IP address. Currently in Mesos all resource (CPU, memory, storage, ports) are owned by a slave. Floating IP wouldn't follow this model so it's something of a paradigm change.

We plan to bring proposals to the Mesos community shortly.

We'd appricate your thoughts too ... what would you like to see?

**Comment by BrianHicks** [comment]
FYI: I'm currently working on a HAProxy config to forward Marathon port mappings to their respective tasks, at least until the work @keithchambers mentions is implemented. Refer to #136 for progress.

**Comment by kenjones-cisco** [comment]
Created PR #194 that enables configuring the ports available by applications within the mesos-followers using mesos resources.
I tested on CCS and verified through actual mesos-follower logs that the configurations were applied correctly.

**Comment by siddharthist** [comment]
@kenjones-cisco Can this be closed? Is this issue fixed with PR #194?

**Comment by kenjones-cisco** [comment]
Sure, I thought it might have been left opening because of the some of the other comments, but this can definitely be closed.
