### ISSUE TITLE
python-novaclient version in requirements.txt

### ISSUE THREAD

**Issue by rida4** [CiscoCloud/microservices-infrastructure#192]
There is a requirement in requirements.txt to have strictly version 2.17.0 for python-novaclient:
python-novaclient==2.17.0.
However, we have version 2.23 installed in our environments. Can we have it changed to :
python-novaclient>=2.17.0 ?

**Comment by stevendborrelli** [comment]
I'm ok with this change. 

@BrianHicks, what are your feelings about >= vs ==?

**Comment by BrianHicks** [comment]
normally I'd say that we should stick with pinned versions. But I've just looked and Ansible doesn't specify a version for this *at all*, so `>=` should work. We might even want to make it `>=2.23`.

**Comment by cdmitri** [comment]
Some more detail behind this one - a couple of days ago while things were working in the morning, after lunch the playbook (site.yml) started failing giving a "unknown argument session in Client(..." (paraphrasing). Due to my previous experience with those clients, I got a hint that it's something with the keystone, nova API. So I installed the latest version which turned out to be 2.23 and things stopped failing...really strange, maybe they've changed something on the cloud at lunch, but I did not have a chance to drill in further. At this point we should test against every DC to see what runs and what fails.

**Comment by BrianHicks** [comment]
It might also be because we upgraded the minimum Ansible version. Having unit tests here would help a lot, but we're not there yet.

**Comment by cdmitri** [comment]
Could be! We were just planning for:

https://github.com/CiscoCloud/microservices-infrastructure/issues/163
https://github.com/CiscoCloud/microservices-infrastructure/issues/178

With first priority having dedicated clusters for full rebuild and CI daily testing of all feature branches, team will post the roadmap with the process starting tomorrow. It'll also have extensive logging, so we can mine for things like versions changes or other possible correlations.

Cheers,
D.
