### ISSUE TITLE
Add CA created by security-setup to common locations

### ISSUE THREAD

**Issue by BrianHicks** [CiscoCloud/microservices-infrastructure#228]
Currently, we have to skip verifying certificates in most places, `curl` being the most obvious when debugging (we have to use `curl -k` to skip verification) but it's also effecting everything that talks to consul, like consul-template.

A few items that need to change off of the top of my head:

- [X] create valid certificates for Nginx proxies (possibly for `*.service.consul`)
- [X] change consul-template default config to use CA
- [X] add certs to nginx-marathon
- [x] add certs to nginx-mesos

**Comment by bketelsen** [comment]
It looks to me like you may be required to mount the host's /etc/consul-template/config.d directory in the haproxy container order to accomplish this.

**Comment by BrianHicks** [comment]
we'll probably do something like that, as well as adding it as a CA for OpenSSL.

**Comment by andreimc** [comment]
Hey @BrianHicks I am getting a few errors on the proxy_server on AWS using master:

2015/05/03 10:52:22 [ERR] (view) "services" Get https://consul.service.consul:8500/v1/catalog/services?wait=60000ms: x509: failed to load system roots and no roots provided
2015/05/03 10:52:22 [INFO] (view) "services" errored, retrying in 5s
2015/05/03 10:52:22 [ERR] (runner) watcher reported error: Get https://consul.service.consul:8500/v1/catalog/services?wait=60000ms: x509: failed to load system roots and no roots provided
2015/05/03 10:52:22 [INFO] (runner) running
2015/05/03 10:52:22 [INFO] (runner) missing data for 1 dependencies
2015/05/03 10:52:22 [INFO] (runner) diffing and updating dependencies
2015/05/03 10:52:22 [INFO] (runner) watching 1 dependencies


I am assuming that this is because of the CA root cert is not added to the docker container that runs HAproxy you had something in issue #229 trying to pass it to the container how did you go ?

Regards
Andrei

**Comment by BrianHicks** [comment]
@andreimc what component are those log lines from? The code for this issue is in `feature/verified-ssl` if you'd like to try it, but it's not in any Docker containers yet.

**Comment by andreijs** [comment]
hey @BrianHicks they are from the haproxy-consul docker container 

It is having issues talking to consul

**Comment by BrianHicks** [comment]
@andreijs @andreimc (are you the same person?) Would you please open a separate ticket for this? It's related to the changes on this one, but far enough away that I want to track it separately. Could you attach all logging output as well as what you expected to see when you ran whatever command?

**Comment by BrianHicks** [comment]
fixed partly in master and partly in one of @ChrisAubuchon's branches
