### ISSUE TITLE
Fix Openstack hostname issues

### ISSUE THREAD

**Issue by stevendborrelli** [CiscoCloud/microservices-infrastructure#27]
After reboot, nodes are being named hostname.novalocal, which causes issues with both Marathon and Mesos. 

We need to investigate how to get consistent naming lookups for the hosts.

**Comment by noahjl** [comment]
I believe for the images we'd either want an ephermal disk, or we just need to pass to the instances a user data file at creation - 

http://docs.openstack.org/image-guide/content/ch_openstack_images.html
http://docs.openstack.org/user-guide/cli_config_drive.html

Theory:
Seems like something along the lines of changing terraform/openstack/hosts/main.tf to have a user_data variable for control & worker resources that points to a generated template? 

This also is where we can customize the username for the images, along with opening up PW access, instead of SSH only (not sure if this is desired?). 

Working on proving the scenarios...

**Comment by loshkovskyi** [comment]
@noahjl , are you still working on this? Otherwise, I will probably get into this task.

**Comment by stevendborrelli** [comment]
Closing this, as we write out the /etc/hosts file with proper names.
