### ISSUE TITLE
Move terraform.py to a separate top-level CiscoCloud project

### ISSUE THREAD

**Issue by BrianHicks** [CiscoCloud/microservices-infrastructure#387]
@stevendborrelli suggested today that we move `terraform.py` to it's own repo. I think that could make sense, but wanted to get the team's feedback.

Pros:

 - `terraform.py` is tested separately, and checkins can automatically be tested with Travis or Wercker and their ilk.
 - the inventory module should follow the release schedule of Terraform instead of microservices-infrastructure, and a separate module would allow that
 - separate documentation
 - more cool projects in top-level CiscoCloud, higher discoverability

Cons:

 - how do we get the module into MI for deployments? git submodules seem like an obvious solution, and work for other projects. This creates an extra step for users, though.
 - could create chains of pull request dependencies. (However, we deal with this already for mesos-consul and marathon-consul and it's not too bad.)

I'd like to hear a :+1: or :-1: vote from the following:

 - [ ] @keithchambers 
 - [x] @stevendborrelli 
 - [ ] @ChrisAubuchon
 - [ ] @ryane
 - [x] @brianhicks :+1: (I think it would be a good idea)

**Comment by keithchambers** [comment]
Honestly I would try to KISS and leave it in the same repo.

**Comment by kenjones-cisco** [comment]
I can see both perspectives on this one, but if it is in a repo and actually published to pypi as a project then it is as simple as pip install to integrate and use. 

I was already trying to think through this myself as now I'll need the same plugin within my project for dynamically discovering my env to do deploys of the containers that make of my service. I had built one for working specifically with openstack but now with terraform it makes more sense to leverage that product that comes from it instead of thinking about openstack only.

I think some refactoring is going to be required as right now each and every cloud provider results in another function to map data from terraform into MI. That could be potentially as simple as a template that maps attributes within terraform to MI such that providing the template for a given providers to the plugin enables the necessary mapping.

**Comment by stevendborrelli** [comment]
I actually think it should be in both places. We have conflicting goals:

1) make microservices-infrastructure awesome & easy to use
2) create tools that are useful beyond the project and benefit others

For 1), we want to keep it in the MI repo, and for 2), we'd want it in a separate project. 

If we go with a separate project, we should just copy tested releases into MI so that the user never has to do anything. I don't want to do git submodules or pip install. 

If I had to pick one, it would be to keep it in MI, as that is our highest priority. I'm also ok with separate project & copying in to MI.

**Comment by tayzlor** [comment]
We're looking at this (or something very very similar) as well as part of https://github.com/Capgemini/Apollo. There might be an opportunity to collaborate here on a separate 'terraform inventory' project ?

**Comment by BrianHicks** [comment]
@tayzlor: that sounds like a great opportunity to collaborate. Worst case
we can share changes between repos, but it sounds like it would be best to
separate the code into a common repo for that.

@steve: there are enough maintenance tasks (releases, doc building, etc)
that I've been thinking we need a makefile or something to standardize.
This sounds like an ideal rule!

Overall I'm surprised at people saying they'll need it in a separate
project. @kenjones-cisco's comment included, we'd need to include it in
three different projects. Three tends to be my cutoff for extracting common
code into a separate module, so I'm going to go ahead and do that unless
anyone has any more objections.

@keithchambers: I think that with the level of copying it might actually be
simpler to have an authoritative master copy, to cut down on confusion from
duplicates. Does that address your concern?

**Comment by stevendborrelli** [comment]
@BrianHicks so we are doing the separate project?

@tayzlor collaboration sounds great. I think there are a few more places we can share ideas and code.

**Comment by BrianHicks** [comment]
Yeah, I think so in this case. I'll get it set up on Monday. For now we can release versions in lock-step with MI, so 0.3.0 will be released first.

**Comment by BrianHicks** [comment]
I've copied `terraform.py` to a new repo, we will copy it in for releases.

https://github.com/CiscoCloud/terraform.py
