### ISSUE TITLE
Check ssh key settings in ansible.cfg

### ISSUE THREAD

**Issue by stevendborrelli** [CiscoCloud/microservices-infrastructure#485]
Came from hacker news discussion: 

"In ansible.cfg, is a default of "host_key_checking = no" and "record_host_keys = no" a good idea?"

Investigate removing these settings.

**Comment by michaeltchapman** [comment]
I agree this is not a good default for production, but it might need to remain on in the CI env where the pool of IPs might be re-used.

**Comment by stevendborrelli** [comment]
I'm worried that turning these features on will cause operational problems. Especially since many users just type 'yes' or delete the keys in `.ssh/known_hosts`. 

We also need to test how terraform behaves when nodes are deleted. 

mi-worker-03 is deleted, then the user decides to grow the cluster. Does `terraform apply` recreate mi-worker-03, causing the ssh key to have a conflict?

**Comment by stevendborrelli** [comment]
On further thought, to MITM on a SSH key:

1) you would need to modify the cloud resource that terraform pulls from, or update the .tfstate file. 
2) Since Ansbile uses ssh keys, you'd need to deploy a server with the deployment pubkey. 

I think we should update the security docs to alert the user to change this if they care about SSH key host checking and leave it off by default.

**Comment by michaeltchapman** [comment]
I don't think Terraform has anything to do with the MITM situation - it's just requesting resources from a cloud. If the cloud provides the same IP as before and host key checking is turned on it will result in a failure regardless of whether the cluster is being regrown or rebuilt or if it's two totally separate applications.

Perhaps I'm missing something but I don't see how the cloud resource would need to be modified at all for a MITM of ssh. The attacker needs to get the user's public key and the server's host key and re-route the user's traffic. Now the user has logged into a machine that they think is their microservices VM but is actually some other machine, and when they run ansible it pushes all their credentials onto that node because ansible sees it's blank and thinks it's a master or a worker. The attacker now has access to the actual microservices cluster using the data the user just provided.

**Comment by sinner-** [comment]
The security model of SSH is essentially TOFU (Trust on First Use), as opposed to requiring a CA (Certificate Authority) to verify public keys.

Disabling host key checking and not recording host keys basically changes this model to Trust on Any Use. 

Aside from concerns about MITM, the implications of this model also mean that if a malicious entity compromised one of the microservices hosts the attacker may be able to pretend to be a different host. Since all microservices hosts will be on an unauthenticated, shared Layer2 network it is possible for the malicious host to use ARP cache poisoning and DNS spoofing to trick ansible and/or administrators into logging into the malicious host as if it was a different (more important) host.

This may, or may not be ok depending on the thread model adopted by the user. 

Choosing a "secure by default" option would be best practice, the user will only need to update their known_hosts file when a microservices host is rebuilt and it should be possible to provide some automation around this, e.g.

"You have chosen to rebuild host foobar001, removing public key for foobar001 from .ssh/known_hosts".
