### ISSUE TITLE
Override consul data center name

### ISSUE THREAD

**Issue by eirslett** [CiscoCloud/microservices-infrastructure#488]
I'm bootstrapping a data center at digitalocean, in the "ams3" zone. But I want to define the name as "amsterdam0" in consul. How can I override that property?

**Comment by stevendborrelli** [comment]
In the terraform.yml file, you can set the `consul_dc` var to what setting you want it to be. Make sure that your `consul_acl_datacenter` var matches your DC. 

The `consul_dc` var is locaed in `roles/consul/defaults/main.yml`

**Comment by BrianHicks** [comment]
here's the prose version of that: http://microservices-infrastructure.readthedocs.org/en/latest/components/consul.html#consul_dc

**Comment by BrianHicks** [comment]
@eirslett we were testing this today and found a bit of a bug. Setting `consul_dc` won't really do you much good since it doesn't change the group name for the servers (it used to.) To *actually* change the DC name, change the `datacenter` variable in your Terraform state. The bug I'm referring to is that datacenter wasn't supported on DO until just now. Would you mind trying out the `feature/digitalocean-dc` branch and letting us know how you get on with it?

A configuration sample:

```
module "do-hosts" {
  source = "./terraform/digitalocean/hosts"
  ssh_key = "${module.do-keypair.keypair_id}"
  datacenter = "amsterdam0"

  region_name = "ams3" # this must be a region with metadata support
  control_count = 3
  worker_count = 3
}
```

**Comment by eirslett** [comment]
Thanks a lot! That worked! :-)
So it should be okay to merge the feature branch.
