### ISSUE TITLE
Automated builds are failing

### ISSUE THREAD

**Issue by stevendborrelli** [CiscoCloud/microservices-infrastructure#635]
@ohal, it looks like a lot of the automated builds from pull requests end up in a failure state. Could you look into it? 

I saw this from the Jenkins logs of http://173.39.214.186/job/PR-to-master-CCS-MI-US-INTERNAL-1-QA-1/191/

```RUN TERRAFORM SILENTLY
Get: file:///home/jenkins/slave/workspace/PR-to-master-CCS-MI-US-INTERNAL-1-QA-1/terraform/openstack/keypair
Get: file:///home/jenkins/slave/workspace/PR-to-master-CCS-MI-US-INTERNAL-1-QA-1/terraform/openstack/hosts
Build step 'Execute shell' marked build as failure```

**Comment by ohal** [comment]
i'm on it
actually, this is bash below and it only suppresses the output from terraform
```bash
#!/bin/bash

echo RUN TERRAFORM SILENTLY
terraform get
terraform plan &> /dev/null
terraform apply &> /dev/null

```

**Comment by ohal** [comment]
unfortunately, there were no logs from terraform to investigate, however, I saw such na issue when key-pair was not deleted after old deployment, so far I did:
- upgraded to terraform 0.6.3
- enabled DEBUG log and log rotation to further investigation

now it deploys well, however there is broken build because the nodes are inaccessible using ssh
http://173.39.214.186/job/COMMIT-to-master-CCS-MI-US-INTERNAL-1-QA-1/145/robot/report/log.html
this might be an issue with openstack, will see tomorrow or after several builds

**Comment by siddharthist** [comment]
@ohal Is there any progress on this? 9/18 of our current PRs are still failing.

**Comment by siddharthist** [comment]
@ohal Still wondering about the status of this ticket. Is anybody working on this? Maybe we just want to remove the webhook until automated testing is ready either via drone or Jenkins?

**Comment by siddharthist** [comment]
Closing in favor of #1091
