### ISSUE TITLE
Rename hosts in inventory files

### ISSUE THREAD

**Issue by stevendborrelli** [CiscoCloud/microservices-infrastructure#69]
Host naming is very limited, we can only have 5 hosts in each dc. 

Refactor host names so we can provision a large number of hosts in each DC without conflicts.

**Comment by keithchambers** [comment]
Is this still an issue?

**Comment by stevendborrelli** [comment]
Yes. 

Any good naming schemes? We could do ctl-X and compute-X

**Comment by keithchambers** [comment]
To make sure I'm following -- do you mean that it's not easy to deploy multiple microservices-infrastructure clusters in to the same OpenStack project because the host names would overlap?

Can you think of a simple way to solve this in Ansible?

My hope is that we can avoid predefined host names all together when we move to Terraform.

**Comment by stevendborrelli** [comment]
Right now in our example inventory files, we have host-01 to host-03 as management nodes, and host-04,5 as compute nodes. DC2 starts with host-06, so if you want to have more than a couple of compute nodes in DC1, you will have interleaving hostnames with DC2.

**Comment by keithchambers** [comment]
You can get around this problem by changing the name of the hosts in dc2 so there is no overlap.  I can see how this becomes complicated at scale and exposes oppertunity for operator error.

I'll mark this as an enhancement.

**Comment by BrianHicks** [comment]
Terraform obsoletes this ticket. The inventory is now dynamic, you can name things whatever you want!
