### ISSUE TITLE
Make consul dns more availble

### ISSUE THREAD

**Issue by stevendborrelli** [CiscoCloud/microservices-infrastructure#767]
We can use a host file as an additional source for dnsmasq. 

Idea: write to file every 15 seconds using consul template, so that in the case of a local consul failure, a cache would still be available. 
 
```
#addn-hosts=/etc/banner_add_hosts
```

**Comment by siddharthist** [comment]
A cache is still available and configurable via stale DNS reads (#807). Should we also write to the hosts file?

**Comment by eirslett** [comment]
In my opinion it's better to use consul's own fallback cache. The reason is that I feel the added complexity of consul-template + /etc/hosts wouldn't justify the small increase in availability you would get. The only improvement you would get, is in case the consul agent process has crashed; but I think systemd restarts consul automatically now anyways?

**Comment by Zogg** [comment]
In environment which is occupied mostly with short-lived containers /etc/hosts would out-date sooner than would provide measurable benefit.

In environment with long lived containers /etc/hosts actually might provide a bacup at critical moment.

**Comment by stevendborrelli** [comment]
Thanks for the feedback. I think I am going to close this issue with a wontfix.
