### ISSUE TITLE
Implement NTP time sync on servers

### ISSUE THREAD

**Issue by stevendborrelli** [CiscoCloud/microservices-infrastructure#811]
Implement ntp on all Mantl nodes to ensure system clocks aren't drifting. 

As a default, we could use pool.ntp.org, and allow users to configure custom ntp servers. 
http://www.pool.ntp.org/en/

Any opinions on this?

**Comment by eirslett** [comment]
+1

**Comment by saswatp** [comment]
Guess we don’t need that feature for NTP. 
CentOS7 by default has chronys running as ntp client and it does secure time sync. with centos ntp server. So , I guess we are okay. 

service chronyd status
Redirecting to /bin/systemctl status chronyd.service
chronyd.service - NTP client/server
Loaded: loaded (/usr/lib/systemd/system/chronyd.service; enabled)
Active: active (running) since Fri 2015-11-13 18:37:45 UTC; 32min ago
Process: 518 ExecStartPost=/usr/libexec/chrony-helper add-dhclient-servers (code=exited, status=0/SUCCESS)
Process: 502 ExecStart=/usr/sbin/chronyd -u chrony $OPTIONS (code=exited, status=0/SUCCESS)
Main PID: 507 (chronyd)
CGroup: /system.slice/chronyd.service
└─507 /usr/sbin/chronyd -u chrony
Nov 13 18:37:45 ip-10-0-60-72.ec2.internal chronyd[507]: chronyd version 1.29.1 starting
Nov 13 18:37:45 ip-10-0-60-72.ec2.internal chronyd[507]: Linux kernel major=3 minor=10 patch=0
Nov 13 18:37:45 ip-10-0-60-72.ec2.internal chronyd[507]: hz=100 shift_hz=7 freq_scale=1.00000000 nominal_tick=10000 slew_delta_tick=833 max_tick_bias=1000 shift_pll=2
Nov 13 18:37:45 ip-10-0-60-72.ec2.internal chronyd[507]: Frequency -6.214 +/- 0.060 ppm read from /var/lib/chrony/drift
Nov 13 18:37:45 ip-10-0-60-72.ec2.internal systemd1: Started NTP client/server.
Nov 13 18:38:19 ip-10-0-60-72.ec2.internal chronyd[507]: Selected source 108.61.73.243
