### ISSUE TITLE
Clarify instructions regarding Terraform environment variables

### ISSUE THREAD

**Issue by BrianHicks** [CiscoCloud/microservices-infrastructure#864]
See #383 - a quirk of Terraform means that our default configurations (the ones with blank authentication variables for OpenStack) won't work if the user wants to use environment variables instead. The docs should be updated to reflect this.

**Comment by stevendborrelli** [comment]
Should we just encourage the use of environment vars of a terraform.tfvars file? It seems like a lot of extra work to duplicate tenant data into the sample files.

**Comment by BrianHicks** [comment]
If I understand the configuration model correctly, given this:

```tf
provider "aws" {
  access_key = ""
  secret_key = ""
  region = ""
}
```

If you want to use environment variables, all you would have to do is this:

```tf
provider "aws" {
  region = ""
}
```

So we should document that, yeah?

**Comment by kenjones-cisco** [comment]
Another element I learned a while back about Terraform, it will append each of the files together (https://www.terraform.io/docs/configuration/load.html) when it starts to handle `get`, `plan`, `apply`. As such all the common parts that get duplicated between most of the files like:

```
variable auth_url {}
variable tenant_id {}
variable tenant_name {}

provider "openstack" {
  auth_url = "${ var.auth_url }"
  tenant_id = "${ var.tenant_id }"
  tenant_name = "${ var.tenant_name }"
}
```

Could all be placed in the top file `openstack.sample.tf`

Also to minimize the number of files to be modified, all the values that can be configured could be placed in a `.tfvars` file, such that whether someone selects `openstack.sample.tf` or `openstack-floating.sample.tf` they only have to change the one `openstack.sample.tfvars` file.

Another great feature of Terraform is the concept of [overrides](https://www.terraform.io/docs/configuration/override.html ). So that for different environments like dev, test, prod, the override file can be loaded. Definitely some information to be referenced for those trying to figure that out.

**Comment by stevendborrelli** [comment]
Can you look at #901 and see if it helps with this? I can deploy only with env vars now, without having to add anything to the files.

**Comment by sehqlr** [comment]
Could #1114 help with this, also? We could document tf vars usage there.

**Comment by stevendborrelli** [comment]
We can close this now that #901 is merged. The older .tf configs will be deprecated.
