### ISSUE TITLE
GlusterFS server nodes do not come up correctly after reboot

### ISSUE THREAD

**Issue by BrianHicks** [CiscoCloud/microservices-infrastructure#892]
As documented in 179ed27, GlusterFS server nodes are not reboot-proof and have to be started separately after the boot is finished.

Conversation on the gluster-users mailing list that will hopefully lead to a resolution of this ticket: http://www.gluster.org/pipermail/gluster-users/2015-December/024514.html

**Comment by BrianHicks** [comment]
If there are any experienced Gluster users reading this, I'd love some help in debugging this more. Please leave a comment here and we'll get in touch.

**Comment by justinclift** [comment]
If you're up for paid GlusterFS assistance, there are places who can help:

&nbsp; &nbsp; http://www.gluster.org/consultants/

:smile:

**Comment by larry-svds** [comment]
I believe the pull request I just made covers this.  https://github.com/CiscoCloud/microservices-infrastructure/pull/952

I was referencing bug 872 but it seems to fix the problems for me.  In the convo above.. they are using consul.  So it could be the same circular dependency between the two unit files as discussed in my pull request.

There is another issue as well in that the default sudoers file requires that you have a tty and so the gluster health check is failing.   Just a heads up that if you use the pull, people might have trouble since it is dependent on consul seeing a healthy gluster before serving out glusterd.service.consul. 

I need to search the existing issues to see if its already here and then I'll add it.

**Comment by larry-svds** [comment]
Didn't see the issue so created one.  https://github.com/CiscoCloud/microservices-infrastructure/issues/953  I think this might also be part of some peoples problem with glusterfs on centos 7.1 with consul as discussed here.

**Comment by eirslett** [comment]
There are many issues like "XXX does not survive a reboot". Maybe the CI environment should run the ansible playbook "reboot-hosts.yml" after provisioning, to verify that everything survived the reboot?

**Comment by avnik** [comment]
I believe we can close it, as well as #872

Also it part of wider problem, we need to depend our boot units against consul+dnsmasq, but also it require  _working- consul (iow -- seeing peers, and elected leader), not just started one

**Comment by ryane** [comment]
fixed by #928. @avnik can you open a new issue in the backlog for the wider problem?
