### ISSUE TITLE
.DS_Store file available at mantl-ui

### ISSUE THREAD

**Issue by AndriiOmelianenko** [CiscoCloud/microservices-infrastructure#960]
Hello,

After provisioning cluster from latest master-branch vulnerability seems to be created in Mantl-UI.

Every control node at 80 port (where mantlui is running) has `.DS_Store` file available to download.
```
http://<control-node-address>/.DS_Store
```

The .DS_Store file is a Mac OS X metadata file providing information for a folder.
Certain configurations of Apple MacOS X contain a vulnerability which could allow an attacker to obtain sensitive information about your system, including system configuration settings, installed applications, etc.
Any directory in the file-system may contain the hidden object, `.DS_Store`. This object is created when a local user views a given directory using the Finder, and it contains sensitive information, such as a list of files stored there.
A remote attacker can read this directory content information by submitting a URL to the vulnerable host's Web service in the following format: `http://www.example.com/target_directory/.DS_store`.

This vulnerability can also affect webservers which host content is copied from a developer's MacOS X machine.

**Comment by corebug** [comment]
@ryane can you please take a look?

**Comment by stevendborrelli** [comment]
I believe @ryane already has a fix in the upstream project at https://github.com/CiscoCloud/nginx-mantlui/pull/10. We can use this ticket to track inclusion here.

**Comment by ryane** [comment]
see #961. there is a new 0.6.0.1 version of the image that does not contain the DS_Store files. 

We have a new version of nginx-mantlui that works with the latest mesos and marathon versions that is included in #955. The image is also updated in that PR.

**Comment by ryane** [comment]
thanks for pointing this out!

**Comment by matjohn2** [comment]
May be worth updating gitignore to prevent accidental re-inclusion (incl elsewhere in the project)?

**Comment by ryane** [comment]
In this case, the problem was not that a DS_Store file was committed into source control but that a DS_Store was inadvertently included in the docker image when it was built. The .dockerignore file is getting support for multi-level wildcards in docker 1.10 but, for now, I updated the Makefile to recursively delete DS_Store files before building the image. What we really need, though, is to automate the build and publishing of docker images from a clean workspace instead of from a developer machine. This is needed across all CiscoCloud repositories; there is a pivotal story (#111152658) tracking this.
